[platformio]
core_dir = ../../../../.platformio-home

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
lib_deps =
  ble-midi-input=${sysenv.BLE_MIDI_INPUT_PACKAGE}
