[platformio]
core_dir = ../../../../.platformio-home

[env:esp32dev]
platform = platformio/espressif32@7.0.1
board = esp32dev
framework = arduino
lib_deps =
  ble-midi-input=${sysenv.BLE_MIDI_INPUT_PACKAGE}
  EmbeddedMusicFirmwareContracts=https://github.com/fczuardi/embedded-music-experiments.git#154035d94df99ab05c3eeb7eb144bf2012972ada
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
  NimBLE-Arduino
