[platformio]
core_dir = ../../../../.platformio-home

[env:esp32dev]
platform = platformio/espressif32@7.0.1
board = esp32dev
framework = arduino
lib_deps =
  ble-midi-input=${sysenv.BLE_MIDI_INPUT_PACKAGE}
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
  NimBLE-Arduino
