[platformio]
default_envs = m5stick-cplus2

[env:m5stick-cplus2]
platform = platformio/espressif32@7.0.1
board = m5stick-cplus2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5Unified@0.2.17
  lathoub/BLE-MIDI@2.2
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
  NimBLE-Arduino
