[platformio]
core_dir = ../.platformio-home
default_envs =
  m5stick-cplus2
  m5stack-core-gray

[env]
lib_deps =
  EmbeddedMusicFirmwareContracts=https://github.com/fczuardi/embedded-music-experiments.git#154035d94df99ab05c3eeb7eb144bf2012972ada

[env:m5stick-cplus2]
platform = platformio/espressif32@7.0.1
board = m5stick-cplus2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
  -pipe
lib_deps =
  ${env.lib_deps}
  m5stack/M5Unified@0.2.17
  lathoub/BLE-MIDI@2.2
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
  NimBLE-Arduino

[env:m5stack-core-gray]
platform = platformio/espressif32@7.0.1
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
  -pipe
lib_deps =
  ${env.lib_deps}
  m5stack/M5Unified@0.2.17
  lathoub/BLE-MIDI@2.2
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
  NimBLE-Arduino

[env:native]
platform = platformio/native@1.2.1
test_framework = unity
test_build_src = yes
build_src_filter =
  -<*>
  +<ActiveNotes.cpp>
  +<AppState.cpp>
  +<MidiNoteName.cpp>
  +<MidiNoteEventFactory.cpp>
