[platformio]
core_dir = ../../../.platformio-home
default_envs = native

[env]
lib_deps =
  firmware-contracts=https://github.com/fczuardi/embedded-music-experiments.git#c9bde598cff9

[env:native]
platform = platformio/native@1.2.1
test_framework = unity
test_build_src = yes
build_src_filter =
  -<*>
  +<MidiNoteEventFactory.cpp>
  +<BleMidiPacketParser.cpp>
