[platformio]
core_dir = ../../../.platformio-home
default_envs =
  m5stick-cplus2
  m5stack-core-gray

[env:m5stick-cplus2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stick-cplus2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.variant = m5stack_stickc_plus2
build_flags =
  -pipe
  -D BLE_MIDI_DEVICE_NAME='"M5 Plus2 MIDI RX"'
lib_deps =
  ble-midi-input=file://../../packages/ble-midi-input
  m5stack/M5Unified@0.2.17

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -pipe
  -D BLE_MIDI_DEVICE_NAME='"M5 Gray MIDI RX"'
lib_deps =
  ble-midi-input=file://../../packages/ble-midi-input
  m5stack/M5Unified@0.2.17

[env:native]
platform = platformio/native@1.2.1
test_framework = unity
test_build_src = yes
build_src_filter =
  -<*>
  +<ActiveNotes.cpp>
  +<AppState.cpp>
  +<MidiNoteName.cpp>
lib_deps =
  firmware-contracts=https://github.com/fczuardi/embedded-music-experiments.git#c9bde598cff9
